### ISSUE TITLE
Update death verification for a unit

### ISSUE THREAD

**Issue by Iruuka** [aMytho/brave-frontier-godot#27]
With the actual implementation of the death in fight, the game wait until a full team turn has ended before looking to dead unit.
This means, when 1 unit attack an enemy unit, the enemy unit isn't considered dead until all the team unit have played.

Maybe we could change the way it is done by looking after every end of animation. But because of that, we could have some nul problem or impossibility.

A one way of thinking i got was we could add an increment to the enemy unit we attack. While the increment is > 0 than 0, we wouldn't look if it's dead yet, because the unit is still under attack. Once no units are attacking it, we would check for their potential death (or send a signal to say "hey i'm dead") and kill them. This way, we can, with 3 characters, attack with 2 units on 1, see it die and then we can attack another enemy unit with the last unit we have.

All of this is my memory from the previous game. Enemies would die during the turn of the player. It wasn't implement in #21 for no precise reason but facility.
If needed, I can try to explain better in the issue if you can't see what is done today and what would be good

**Comment by Iruuka** [comment]
Hello @aMytho ,

I have some idea for this issue :

- when a unit attack another one, it will increment a counter of "targeted attack" on the target
- When the attack has been dealth, the target will see their counter be reduced and the game will see if the unit is dead or not. Therefor, it will allow a unit to die during a round
- - This also mean we'll need to change the way to end a stage
- In the field_unit.gd, we'll have to add 2 stats : the place_ID of the targeted unit it is attacking and the "targeted attack" talked before.
- - so when we are finishing an attack, we'll get the place_id of the targeted id of the attacking unit and get the number of targeted attack of the targeted unit. If the "targeted attack" = 0 after the attack of the unit, we'll check if the unit is dead. And if yes and still not targeted, we'll kill it.
- - after this verification, we would check if they're still targeted team's unit left. If yes, nothing. If no, we would end the stage.


I don't know if the idea is understandable. But I'ld like to be asign to this issue. I'll try to do a sketch when I have times

Have a good Day/Night !

**Comment by aMytho** [comment]
I agree that it needs to be changed. I started some work on this for the death animation (it made it easier to see the unit vfx), but I ended up removing it since it didn't belong in the PR and it was pretty late. If you want to try it, you are more than welcome to. Since I switched my PR back to just the animation it shouldn't create any big merge conflicts.

My current idea is to switch a lot of the attack logic from our direct method calls to be more reliant on signals. I realized that most units don't have a single attack like our slimes/selena. Most attacks (especially brave bursts) actually do damage in several attacks, rather than all at once. I thought of the following signal structure:

- Battle.bd calls attack method on field_unit( or however we normally start the attacks, don't have the code in front of me atm)
- Units emits `StartedMoving`
- When units reaches enemy emit `ReachedTarget`
- Emit `BeganAttack`
- For every individual attack (just one since we don't have any distinction between them) emit `EnemyDamaged` with the unit and the amount. (If you have a better idea for this, let me know.)
- Once the attacks are finished, emit `AttackComplete`
- Emit `MovingHome`
- When home, remit `MovingComplete`

The battle.gd (or enemies/friendlies) would listen for these and perform the necessary tasks. We would probably need to remove the death signal in the HP check. It would need to be separate so we only check once the player has stopped attacking.

This is a lot of signals, but we will need a lot of this information. As you mentioned, the unit doesn't die and the round doesn't end if a unit is still attacking a target (likely so they can farm materials). We need to delay the HP calculation and death check until the units have finished their movements/attacks. I partially understand the rest, but I'll need to pay it more attention when I return home.

Edit: We could probably remove the death signal from the HP check so we can update the unit's HP in real-time, without needing to start the death animation. Once we know the action has stopped, we can then check if the unit is dead.

**Comment by Iruuka** [comment]
If you're not finish with the "wait" feature until tomorrow night, i'll take this issue then ! (It's 9pm gmt+2 now)

I'll try to see and follow all the ideas you've given then

**Comment by aMytho** [comment]
If you want, I can add a slight delay after the death animation has finished. However, the rest of the issues will require reworking the attack/turn systems. Since we don't wait for the animation, it only affects the vfx, not the actual turn system.

A related issue is that it is possible for a unit to be killed, the turn ends, and in the next stage the unit in the same place fades away. They are still there, just invisible. I think I caused that issue though.

Edit: Yep, the additional delay by the death animation allowed that to happen. I'll push a fix.

**Comment by Iruuka** [comment]
I'm starting to work on this. To have the number of hit feature later, i'll add a default value in unit_base.gd.
I'll also try to reproduce what you have done for the death animation for the death verification and damage dealing.

I'll post a draft of the work in a couple of hours and continue tomorrow.

**Comment by Iruuka** [comment]
Hello @aMytho !

The PR for this feature is available here ==> PR https://github.com/aMytho/brave-frontier-godot/pull/34 .
There is one old feature that is "broken" and one new feature that doesn't* work "too fast" (everything is in the PR for more info)

I didn't add all the signal you ask, so if you need them in this PR, tell me i'll add them.
Anyway, you can start review the code now, there is just a little problem that I will fix later. Edit : and comment the code.

Have a good Day/Night !

**Comment by aMytho** [comment]
Merged in #34
